### ISSUE TITLE
Missing file in Project

### ISSUE THREAD

**Issue by ghost** [webdriverextensions/webdriverextensions-archetype-quickstart#1]
Error in POM file. It probably should just be ignored as suggested by M2E but I have a second issue and I don't know if it is related.
First issue, POM Error:
Plugin execution not covered by lifecycle configuration: com.github.webdriverextensions:webdriverextensions-maven-plugin:1.0.1:install-drivers (execution: default, phase: generate-sources)

Second issue (related?)
Re-imported project from GitHub and now a file is missing for import. It is causing reference errors. I imported the project last week with no issues but now it isn't compiling.

Import Error:
The import com.github.webdriverextensions.generator.GeneratedWebRepository cannot be resolved

![missingfile](https://cloud.githubusercontent.com/assets/11430434/6941976/b468c9b6-d849-11e4-9ce2-56939da40a3f.png)

**Comment by andidev** [comment]
Does this concern the archetype or the webdriverextensions framework? Looks like you created an issue about the webdriverextensions framework in the archetype github repo.

I'm guessing you are trying to modify or add something to the webdriverextensions framework? If that is the case I can tell that developing the webdriverextensions archetype in Eclipse comes with the two problems that you have ancountered. I'm using Netbeans so I have not encountered those problems. Howerver I can take a look at solving the issues you are having.

The first one is easy to solve. Simply add 

``` xml
<pluginManagement>
            <plugins>
                <!--Eclipse m2e settings (can be removed if you are not using eclipse) -->
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>com.github.webdriverextensions</groupId>
                                        <artifactId>webdriverextensions-maven-plugin</artifactId>
                                        <versionRange>[1.0,)</versionRange>
                                        <goals>
                                            <goal>install-drivers</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <execute>
                                            <runOnIncremental>true</runOnIncremental>
                                        </execute>
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
```

... to the pom.xml to tell Eclipse that it is okey to run the `install-drivers` goal which downloads the drivers. I will add this to the pom.xml myself later tonight so you could just clone it once again if wanted.

The second issue is there cause the framework supports adding WebPages by annotation to a generated WebRepository (the missing file GeneratedWebRepository). This feature is however not documented because this issue with Eclipse. The reason is that Eclipse does not seem to run the following configurated plugin which generates this files

``` xml
            <!-- Run annotation processors on src/test/java sources -->
            <plugin>
                <groupId>org.bsc.maven</groupId>
                <artifactId>maven-processor-plugin</artifactId>
                <version>${maven-processor-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>process-test</goal>
                        </goals>
                        <phase>generate-test-sources</phase>
                        <configuration>
                            <processors>
                                <processor>com.github.webdriverextensions.generator.WebSiteGenerator</processor>
                                <processor>com.github.webdriverextensions.generator.WebRepositoryGenerator</processor>
                            </processors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

Therefore the tests fails to compile since the generated files are missing.

The best thing to do is to abandon Eclipse in favour to NetBeans or IntelliJ cause Eclipse is a bit tricky sometimes :smiley: 
I'm gonna try solving the second issue  as soon as possible. I'll be back!

**Comment by andidev** [comment]
Also please note that you can always compile the project from the console with `mvn clean install`. This issue is only an issue when compiling the project from Eclipse.

**Comment by andidev** [comment]
So I have fixed the pom.xml so that it is possible to import it in eclipse.

Could you please pull the changes and try it out and tell me if it is not fixed?

**Comment by ghost** [comment]
I deleted and re-imported from GitHub and then chose "Import Maven
Projects" from the Git-Repositories pane but I get the same results. I went
through and ran the Maven builds, clean, install, test and all seemed to
work. 10 tests were skipped, 1 failed and 90ish passed.

The compile error still exists in the POM at line 207 for <execution> and
it is:
Error executing
(org.bsc.maven:maven-processor-plugin:2.2.4:process-test:default:generate-test-sources)

I'm too new to this to offer any assistance in your debugging efforts. :-(

On Wed, Apr 1, 2015 at 4:17 PM, Anders Steiner notifications@github.com
wrote:

> So I have fixed the pom.xml so that it is possible to import it in eclipse.
> 
> Could you please pull the changes and try it out and tell me if it is not
> fixed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/webdriverextensions/webdriverextensions-archetype-quickstart/issues/1#issuecomment-88634207
> .

## 

_Jim_

**Comment by andidev** [comment]
Strange, it should be resolved. Could you please provide the pom.xml just in case.

Are you using the latest eclipse version? Are you using any specific eclipse settings?

**Comment by andidev** [comment]
I'll try to install a clean eclipse and clone a fresh project and see how that works. I'll be back with the result.

**Comment by andidev** [comment]
I just tried it again with a clean fresh install of Eclipse and it seems to work. I only encountered one problem after importing the maven project. This was however solved by refreshing the project. I did however not encounter any errors in the pom.xml. Are you sure you imported the newly cloned project and not the old one?

This is what I did:
1. Removed the current Eclipse from my Mac
2. Installed the latest version of Eclipse
3. Cloned the project with the command `git clone https://github.com/webdriverextensions/webdriverextensions` from the terminal
4. Imported the project as a Maven project with "File" -> "Import" -> "Existing Maven Projects" -> "Selected the cloned webdriverextensions directory as the root"
5. Waited for Eclipse to finnish the import
6. Got 100 errers of 152 items in the problems view (Eclipse does not get that files have been generated yet)
7. Refreshed the project with "Right click on project" -> "Refresh"
8. All errors gone

Regarding the failing test it could be because the tests are run in parallell and they sometime fail cause of some time issue. Try removing parallell configuration in the pom.xml. I.e. remove this:

``` xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <parallel>all</parallel>
                    <threadCount>4</threadCount>
                    <failIfNoTests>false</failIfNoTests>
                </configuration>
            </plugin>
```

**Comment by ghost** [comment]
That worked. I just did the "Refresh" from Eclipse.
I had one warning for an Import that was never used but that is all.
I should have tried that from the git go... :-)

I know some programming details and understand the concepts like reuse and
polymorphism a little bit. I really like how you've structured your project
and I'm still trying to understand how you extended Selenium with
"Implements" but I have a question if you don't mind answering.

In some older programming languages, I could perform additional tasks while
executing a method.
For example, I could execute the Selenium Click but the local function I
have called "Click" will execute first.

Call Selenium.Click but my Function "Click" is called instead

"Click" (local function) {
    In that function, I could do "abc".
    Selenium.Click again and the actual Selenium "Click" executes.
    Return from my function Click
}

I've seen some stuff on overriding but that seems more complicated than
what I need. Is there any approach in Java to do what I described without
implementing an Interface for Selenium like you did for your framework or
what is the right terminology and I'll research it more?

I never mentioned it but thanks very much for sharing your code!
Jim

On Fri, Apr 3, 2015 at 6:32 AM, Anders Steiner notifications@github.com
wrote:

> I just tried it again with a clean fresh install of Eclipse and it seems
> to work. I only encountered one problem after importing the maven project.
> This was however solved by refreshing the project. I did however not
> encounter any errors in the pom.xml. Are you sure you imported the newly
> cloned project and not the old one?
> 
> This is what I did:
> 1. Removed the current Eclipse from my Mac
> 2. Installed the latest version of Eclipse
> 3. Cloned the project with the command git clone
> https://github.com/webdriverextensions/webdriverextensions from the
> terminal
> 4. Imported the project as a Maven project with "File" -> "Import" ->
> "Existing Maven Projects" -> "Selected the cloned webdriverextensions
> directory as the root"
> 5. Waited for Eclipse to finnish the import
> 6. Got 100 errers of 152 items in the problems view (Eclipse does not get
> that files have been generated yet)
> 7. Refreshed the project with "Right click on project" -> "Refresh"
> 8. All errors gone
> 
> Regarding the failing test it could be because the tests are run in
> parallell and they sometime fail cause of some time issue. Try removing
> parallell configuration in the pom.xml. I.e. remove this:
> 
> ```
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-surefire-plugin</artifactId>
>             <version>${maven-surefire-plugin.version}</version>
>             <configuration>
>                 <parallel>all</parallel>
>                 <threadCount>4</threadCount>
>                 <failIfNoTests>false</failIfNoTests>
>             </configuration>
>         </plugin>
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/webdriverextensions/webdriverextensions-archetype-quickstart/issues/1#issuecomment-89260970
> .

## 

_Jim_

**Comment by andidev** [comment]
I think you are searching for some sort of Aspect Oriented Programming aka AOP.
But I don't know if it is possible to use on the selenium WebElements.

An alternative would be to use WebDriverExtensions and extend the WebComponent class and override all methods in it and then use it instead of WebElements e.g.

``` java
import com.github.webdriverextensions.WebComponent;

public class CustomWebElement extends WebComponent {
    @Override
    public void click() {
        System.out.println("do something before");
        super.click();
        System.out.println("do something after");
    }

    // ...all other WebElement methods to override
}
```

...and then use it in a test e.g.

``` java
import com.github.andidev.mavenproject1.CustomWebElement;
import static com.github.webdriverextensions.Bot.click;
import static com.github.webdriverextensions.Bot.open;
import com.github.webdriverextensions.junitrunner.WebDriverRunner;
import com.github.webdriverextensions.junitrunner.annotations.Firefox;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.support.FindBy;

@RunWith(WebDriverRunner.class)
@Firefox
public class MyTest {

    @FindBy(css = "a-css-selector")
    CustomWebElement buttonToClick;

    @Test
    public void aTest() {
        open("http://www.mysiteurl.com");
        click(buttonToClick); // will call click method in the CustomWebComponent class
    }
}
```
